# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('prot', models.IntegerField(default=0)),
                ('fats', models.IntegerField(default=0)),
                ('carb', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
            ],
        ),
    ]
